coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 2%
        informational: true

    patch:
      default:
        target: 90%
        informational: true

comment: false
